# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-its/all/rspec-its.rbi
#
# rspec-its-1.3.0

module RSpec
end
module RSpec::Its
  def its(attribute, *options, &block); end
end
module RSpec::Core::SharedContext
  include RSpec::Its
end
