# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module RubyChessBoard::Board::BoardFiles; end
module RubyChessBoard::Coordinate::CoordinateSet; end
module RubyChessBoard::CoordinateSet; end
module T::CompatibilityPatches::RSpecCompatibility::MethodDoubleExtensions; end
module T::CompatibilityPatches::RSpecCompatibility::RecorderExtensions; end
